### ISSUE TITLE
Contact us form

### ISSUE THREAD

**Issue by alexookah** [scottyzen/woonuxt#108]
Are you interested in having contact us gql form in woonuxt?

Just made a [commit](https://github.com/alexookah/cwr-nuxt/commit/c0362b5e169f9878c40246ac469313b093e1e037) in my fork adding a contact us page functionality

allthough this required installing this [plugin](https://github.com/ashhitch/wp-graphql-send-mail)
Not sure if you want to include this as part of woonuxt plugins set. maybe optional?

Let me know if you like this @scottyzen.

**Comment by scottyzen** [comment]
Hi @alexookah,

I just had a look at the form and it looks great! However, I wouldn't put it directly into the woonuxt_base folder for the exact it would prevent other people from customizing it in other ways. For example, someone might want to use a service like Hubspot for their contact form. 

I've used [wp-graphql-send-mail](https://github.com/ashhitch/wp-graphql-send-mail) myself before and I think it's a great way to handle contact forms for these kind of sites. I just want to leave it open so that people can use whatever they want.

Your form could make a great blog post for others to see how extendable WooNuxt is. And hooking into other WPGraphQL plugins.

**Comment by alexookah** [comment]
Great! totally get it! closing this issue to mark it as resolved
