### ISSUE TITLE
Site Performance

### ISSUE THREAD

**Issue by softwarerockstar** [scottyzen/woonuxt#263]
Hi,

I am sure that I have not configured something properly, but I noticed that my test site was loading shop pages (e.g. products, categories) way slower than the demo sites. Upon investigation I see that every time I navigate to one of these pages, my browser (tried both Chrome and Edge) sends off GraphQL requests to the server (please see screenshot for the products page) causing this slowdown. The demo sites do not send these GraphQL requests on the same pages.

If it helps, my WP site is deployed on Cloudways and my frontend on Cloudflare Pages. I am running the latest main branch code from the woonuxt project.

Any insight in helping me figure this out will be deeply appreciated!

![2024-12-11_14-07-41](https://github.com/user-attachments/assets/f9faf300-3bb8-4149-ab95-f7a34a183e85)

**Comment by alexookah** [comment]
It depends of what script you do for deployment in cloudflare pages the woonuxt app. 
In my case I use npm run generate which reads all products on build time and creates static pages so that it's super fast.
If you use nuxi generate. the deployment of Nuxt will be with SSR which also fetches the products real time. which is way slower.

**Comment by softwarerockstar** [comment]
Wow thank you so much @alexookah! I selected defaults presented by CloudFlare and that was my mistake. After editing the build command to `npm run generate` it correctly generates all the pages and the site it superfast just like the demo sites. Thank you once again!!
