### ISSUE TITLE
Cannot read properties of null (reading 'toLowerCase')

### ISSUE THREAD

**Issue by M-GRV** [scottyzen/woonuxt#31]
Hey!

Weird little bug. When using the search I'm seeing this:

`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'toLowerCase')`

Which is strange because nothing was changed on my end for search. Your demo is working fine. I did have a cors issue I solved, but this doesn't seem related. Just checked your source with my page and its exactly the same.

Also speaking on unrelated, any ideas for Algolia integration for faceted search?

**Comment by M-GRV** [comment]
![image](https://user-images.githubusercontent.com/130182174/233656759-2a746562-f619-40d0-ac95-85e4fd3eea82.png)

**Comment by scottyzen** [comment]
Hey @M-GRV. The search should be sorted now. The error was happening when a product was missing a description or a short description. Thanks again for catching it! 👏🏻

Also about the Algolia integration, I have no plans for it for the time being. Mainly because I want to keep everything working relying on as few dependencies as possible. Also, I don't have much experience using it 😅 

It might be something I'll look at in the future.

**Comment by M-GRV** [comment]
Thanks for the reply! Ill keep battle testing this for you :p 

I don't blame you for wanting to keep dependencies low. 

I think woonuxt could benefit from eventually having something in the woonuxt settings plugin that can turn on maybe certain optional dependencies. Might be a way to to do it.

Algolia is cool and allows you to do faceted searchs on woocommerce products from a WP plugin. So you can literally type for example in search: Green shirts for under $30 and it would apply the filters and return the search.  Pretty cool and they have a free plan. 

Just a thought :)

Thanks again!
