### ISSUE TITLE
Question: Nuxt webp

### ISSUE THREAD

**Issue by alexookah** [scottyzen/woonuxt#99]
Hi! Really nice implementation!
I was wondering: Why aren't you using [NuxtImage](https://image.nuxt.com/usage/nuxt-picture) to leverage image processing so that images get converted to webp?

**Comment by scottyzen** [comment]
Hi @alexookah, I'm not sure what your not seeing. ```<NuxtImg />``` is used throughout the site. And it's using webp wherever it can. Some svg's are the only exceptions.

**Comment by alexookah** [comment]
I was referring to [this](https://github.com/scottyzen/woonuxt/blob/master/woonuxt_base/components/cartElements/CartCard.vue#L24C1-L32)
and also [these](https://github.com/search?q=repo%3Ascottyzen%2Fwoonuxt%20%3Cimg&type=code).

Any reason why the product images are not using NuxtImg ?

**Comment by scottyzen** [comment]
Some images need to to use the default img tag because they would be pre-rendered at build time. These parts of the app would be more dynamic elements also. For example: In order for me to use the <NuxtImg /> component in the CartCard.vue component I would need to statically render all the images on a seperate page or something like that. But I think that would just increase the build time without much upside.
